apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html

    - name: nginx-content
      image: nageshaab/joinraghu:v1
      volumeMounts:
        - name: nginx
          mountPath: /usr/share/nginx/html

  volumes:
    - name: nginx-path
      emptyDir: {}