apiVersion: v1
kind: Pod
metadata:
  name: pod-03
spec:
  containers:
    #container reading the data
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  initcontainers:
    - name: nginx-content
      image: nageshaab/join:v2
      volumeMounts:
        - name: nginx-path
          mountPath: /usr/share/nginx/html
  #common volume/shared volume
  volumes:
    - name: nginx-path
      emptyDir: {}
